---
# tasks file for ansible-vsftpd
- name: install vsftpd
  apt: name={{ item }} state=latest cache_valid_time=3600 update_cache=yes
  with_items:
    - vsftpd
  when: ansible_pkg_mgr == "apt"

- name: install vsftpd
  yum: name={{ item }} state=latest
  when: ansible_pkg_mgr == "yum"
  with_items:
    - vsftpd

- name: install db4 utils
  yum: name=db4-utils state=latest
  when: auth_berkeley_db and ansible_pkg_mgr == "yum"

- name: install db4 util
  apt: name=db4.8-util state=latest
  when: auth_berkeley_db and ansible_pkg_mgr == "apt"

- name: install libpam-pwdfile
  yum: name=libpam-pwdfile state=latest
  when: auth_pwdfile and ansible_pkg_mgr == "yum"

- name: install libpam-pwdfile
  apt: name=libpam-pwdfile state=latest cache_valid_time=3600 update_cache=yes
  when: auth_pwdfile and ansible_pkg_mgr == "apt"

- name: create directory for user configuration
  command: mkdir -p {{ vsftpd_user_config_dir }} creates={{ vsftpd_user_config_dir }}

- name: create directory for key local_root from vsftpd.conf
  command: mkdir -p {{ vsftpd_local_root }} creates={{ vsftpd_local_root }}

- name: set permissions for local_root
  command: chown root:root {{ vsftpd_local_root }}

- name: copy file for PAM service
  template: src=vsftpd.pam.j2 dest=/etc/pam.d/vsftpd mode=644 backup=yes

- name: copy script the vsftpd-user
  template: src=vsftpd-user.j2 dest=/sbin/vsftpd-user mode=755

- name: add test user of the ftp
  tags: testuser
  command: /sbin/vsftpd-user add {{ test_user }} {{ test_user_password }} creates=/etc/vsftpd
  when: test_user_is_enable

# will be create backup file if already exist
- name: copy config file of the vsftpd
  template: src=vsftpd.conf.j2 dest=/etc/vsftpd.conf mode=644 backup=yes
  notify:
    - restart vsftpd
